### ISSUE TITLE
Console spammed by sponge issue with your pl

### ISSUE THREAD

**Issue by pjindras** [IzzelAliz/AmberShop#37] opened 2020-07-25 11:36 UTC
**Describe the bug**
My console is instantly spammed by sponge with some warn issues of amber shops 

**To Reproduce**
Idk, just run it.

**Environment:**
 - Sponge version: 1.12.2-2838-7.2.3
 - AmberShop version 1.1.6

log:
https://pastebin.com/y8J0Qtsz

**Comment by IzzelAliz** [comment] 2020-07-25 13:12
Duplicate of #19.

**Closed as completed by IzzelAliz** 2020-07-25 13:12 UTC
